config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'points/coordinates'
  resources :points
  resources :itineraries
end

app/models/itinerary.rb
class Itinerary < ActiveRecord::Base

  belongs_to :start_point, class_name: "Point"
  belongs_to :end_point, class_name: "Point"

  
end

app/models/point.rb
class Point < ActiveRecord::Base

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/itineraries_controller.rb
class ItinerariesController < ApplicationController
  before_action :set_itinerary, only: [:show, :edit, :update, :destroy]

  def index
    @itineraries = Itinerary.all
  end

  def show
  end

  def create
    @itinerary = Itinerary.new

    @itinerary.itinerary_name = params[:itinerary_name]
    @itinerary.avaliable_seats = params[:seats]
    @itinerary.start_point = newpoint(params[:point_a])
    @itinerary.end_point = newpoint(params[:point_b])

    if @itinerary.save
       # render json: @itinerary
    else
      render json: @itinerary.errors, status: :unprocessable_entity
    end
  end

  def destroy
    @itinerary.destroy
    respond_to do |format|
      format.html { redirect_to itineraries_url, notice: 'Point was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
  
  def set_itinerary
    @itinerary = Itinerary.find(params[:id])
  end

  def newpoint (address)
    @point = Point.new
    @point.address = address

    address_field = Geokit::Geocoders::GoogleGeocoder.geocode @point.address
    @point.latitude  = address_field.lat
    @point.longitude = address_field.lng
    
    @point.save
    @point
  end
  
end

app/controllers/points_controller.rb
class PointsController < ApplicationController
  require "geokit"
  before_action :set_point, only: [:show, :edit, :update, :destroy]

  # GET /points
  # GET /points.json
  def index
    @points = Point.all 
      # render json: @points
  end

  # GET /points/1
  # GET /points/1.json
  def show
  end

  # GET /points/new
  def new
    @point = Point.new
  end

  # GET /points/1/edit
  def edit
  end

  # POST /points
  # POST /points.json
  def create
    @point = Point.new(point_params)

    if @point.save
        render json: @point 
      else
        format.html { render :new }
        format.json { render json: @point.errors, status: :unprocessable_entity }
      end
end

  # PATCH/PUT /points/1
  # PATCH/PUT /points/1.json
  def update
    respond_to do |format|
      if @point.update(point_params)
        format.html { redirect_to @point, notice: 'Point was successfully updated.' }
        format.json { render :show, status: :ok, location: @point }
      else
        format.html { render :edit }
        format.json { render json: @point.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /points/1
  # DELETE /points/1.json
  def destroy
    @point.destroy
    respond_to do |format|
      format.html { redirect_to points_url, notice: 'Point was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def coordinates
    @point = Point.new
    @point.address = params[:address]
    # @point.update(point_params)
    address_field = Geokit::Geocoders::GoogleGeocoder.geocode @point.address
    @point.latitude  = address_field.lat
    @point.longitude = address_field.lng
    # renderize the value in json
    render json: @point 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_point
      @point = Point.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def point_params
      params.require(:point).permit(:address, :name, :latitude, :longitude)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/itineraries_helper.rb
module ItinerariesHelper
end

app/helpers/points_helper.rb
module PointsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MoovenApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', defer: true %>
  <%= csrf_meta_tags %>
  <script src="http://maps.googleapis.com/maps/api/js"></script>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/points/_form.html.erb
<%= form_for(@point) do |f| %>
  <% if @point.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@point.errors.count, "error") %> prohibited this point from being saved:</h2>

      <ul>
      <% @point.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/points/edit.html.erb
<h1>Editing point</h1>

<%= render 'form' %>

<%= link_to 'Show', @point %> |
<%= link_to 'Back', points_path %>

app/views/points/index.html.erb
<h1>Listing points</h1>

<table>
  <thead>
    <tr>
      <th>Address</th>
      <th>Name</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @points.each do |point| %>
      <tr>
        <td><%= point.address %></td>
        <td><%= point.name %></td>
        <td><%= point.latitude %></td>
        <td><%= point.longitude %></td>
        <td><%= link_to 'Show', point %></td>
        <td><%= link_to 'Edit', edit_point_path(point) %></td>
        <td><%= link_to 'Destroy', point, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Point', new_point_path %>

app/views/points/new.html.erb
<h1>New point</h1>

<%= render 'form' %>

<div id="container-map">

</div>

<%= link_to 'Back', points_path %>

app/views/points/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Address:</strong>
  <%= @point.address %>
</p>

<p>
  <strong>Name:</strong>
  <%= @point.name %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @point.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @point.longitude %>
</p>

<%= link_to 'Edit', edit_point_path(@point) %> |
<%= link_to 'Back', points_path %>